
node ('3scale') {

    stage ('Checkout') {
        git 'https://github.com/microcks/api-lifecycle.git'
    }

    container('3scale-toolbox'){

        stage("Import OpenAPI") {
            sh '3scale -k import openapi -d 3scale-kskels beer-catalog-demo/api-contracts/beer-catalog-api-swagger.json --override-private-base-url=https://echoapi-3scale-apps.apps.ocp4.kskels.com -t beer-catalog-cli'
        }

        stage("Create an Application Plan") {
            sh '3scale -k application-plan apply 3scale-kskels beer-catalog-cli test-plan-cli -n "Test Plan CLI" --default'
        }

        stage("Create an Application") {
            sh '3scale -k application apply 3scale-kskels 1234567890abcdef --account=john --name="Test Application CLI" --description="Created from the CLI" --plan=test-plan-cli --service=beer-catalog-cli'
        }

        stage("Run integration tests") {
            def output = sh (script: '3scale -k proxy-config show 3scale-kskels beer-catalog-cli sandbox', returnStdout: true)
            def payload = readJSON text: output

            sh "curl -k -f -H \"api-key: 1234567890abcdef\" ${payload.content.proxy.sandbox_endpoint}/beer"
        }

        stage ('Promote') {
            sh '3scale -k proxy-config promote 3scale-kskels beer-catalog-cli'
        }

    }
}
